apiVersion: ecso/v1
kind: Defaults

spec:
  resources:
    cpu: 256
    memory: 512

  replicas: 1

  autoscaling:
    enabled: true
    min: 1
    max: 5
    metrics:
      - type: cpu
        target: 70

  healthCheck:
    path: /health
    interval: 30
    timeout: 5
    healthyThreshold: 2
    unhealthyThreshold: 3

  deployment:
    maximumPercent: 200
    minimumHealthyPercent: 100
    circuitBreaker: true
    rollback: true
