apiVersion: ecso/v1
kind: Environment

metadata:
  name: dev
  cluster: ecso-cluster
  region: us-east-1

spec:
  autoSync: true

  terraform:
    bucket: ecso-terraform-state-085122410972
    key: environments/dev/terraform.tfstate
    region: us-east-1

  aws:
    accountId: "085122410972"
    ecrRegistry: "085122410972.dkr.ecr.us-east-1.amazonaws.com"

  network:
    vpcId: vpc-024f8879c138fa369
    subnets:
      - subnet-06079416fd3647700
      - subnet-08551b817857a3c44
    securityGroups:
      - sg-0a5ef64bf8cba1deb

  loadBalancer:
    targetGroupArn: arn:aws:elasticloadbalancing:us-east-1:085122410972:targetgroup/ecso-test-app-tg/e7d45a19b1f4d2ca

  services:
    test-app:
      image: ecso-test-app
      tag: bca6545
      replicas: 1
      autoscaling:
        enabled: true
      resources:
        cpu: 512
        memory: 1024
      ports:
        - containerPort: 8080
      healthCheck:
        path: /health
      loadBalancers:
        - listenerArn: arn:aws:elasticloadbalancing:us-east-1:085122410972:listener/app/ecso-alb/e15417ca467074a9/ca134d5d685d91b3
          containerPort: 8080
          routing:
            pathPatterns:
              - "/app/*"
              - "/health"
            priority: 200
      env:
        NODE_ENV: development
        APP_VERSION: "1.2.0"

    nginx:
      image: public.ecr.aws/nginx/nginx
      tag: "1.25-alpine"
      replicas: 1
      resources:
        cpu: 256
        memory: 512
      ports:
        - containerPort: 80
      healthCheck:
        path: /
        port: 80
      loadBalancers:
        - listenerArn: arn:aws:elasticloadbalancing:us-east-1:085122410972:listener/app/ecso-alb/e15417ca467074a9/ca134d5d685d91b3
          containerPort: 80
          routing:
            pathPatterns:
              - "/nginx/*"
              - "/static/*"
            priority: 300
            healthCheckPath: /
